name: mofu_audio_metadata
description: Metadata parsing library that supports various audio formats and containers.
version: 0.1.0
repository: https://github.com/MeaninglessCode/mofu_audio_metadata

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  image: ^4.3.0
